language: c
sudo: required
matrix:
  include:
    - env: ARCH=x86_64 ARCH_CMD=linux64
      os: linux
    - os: osx
before_install: |
  case $TRAVIS_OS_NAME in
    linux)
      curl http://dist.crystal-lang.org/apt/setup.sh | sudo bash
      sudo apt-get -q update
      ;;
    osx)
      brew update
      brew tap manastech/crystal
      ;;
  esac
install: |
  sudo apt-get install crystal
script:
  - crystal spec
branches:
  only:
    - master